spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  web:
    locale: en_US
    locale-resolver: fixed

springdoc:
  swagger-ui:
    tags-sorter: alpha
    defaultModelsExpandDepth: -1
  writer-with-order-by-keys: true

design-hub:
  global:
    security:
      token-expiration: 3600
